// Package headers is a chain tracker over a header source: an overlay
// bridge's native /v1 routes (github.com/lightwebinc/overlay-bridge), the
// public WhatsOnChain API, a chaintracks v2 service, a block-headers-service,
// or the chaintracks server an arcade installation embeds.
//
// It is the root of trust for every proof checked against it. A transaction
// is only as trustworthy as the headers its BUMP is checked against, so the
// question of WHO answers "what root does height N commit to" is the whole
// security question, not a configuration detail. A bridge that received the
// headers itself, off the same network that delivered the transaction, needs
// no further check. A source that serves header fields (every other kind)
// is not taken at its word: every header it answers is hashed
// here and must carry the work its bits claim, at or above the network's
// floor, so a lie costs a mined block rather than an edited response.
//
// It speaks HTTP and imports nothing from the bridge. That is deliberate:
// this module has exactly one direct dependency, and an HTTP contract plus a
// vendored fixture is a cheaper coupling than a Go dependency on a service.
// The fixtures in testdata/fixtures are the bridge's own generated bytes,
// copied verbatim, so a change to its wire shape fails here rather than in
// production.
package headers

import (
	"context"
	"crypto/tls"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/bsv-blockchain/go-sdk/chainhash"
	"github.com/bsv-blockchain/go-sdk/transaction/chaintracker"
)

// Client reads block headers from one header source.
type Client struct {
	// Base is the source's base URL, with no path suffix.
	Base string
	// Kind is the dialect Base speaks. The zero value is a bridge's /v1.
	Kind Kind
	// Network sets the proof-of-work floor for a source that serves header
	// fields: Mainnet checks MainnetMinDifficulty, anything else checks each
	// header against its own target only.
	Network string
	// MinDifficulty overrides the network's floor when positive.
	MinDifficulty float64
	// HTTP is optional.
	HTTP *http.Client
	// Timeout defaults to 10s when HTTP is nil.
	Timeout time.Duration
	// Token, when set, is sent as a bearer token on every request: a
	// block-headers-service requires one unless its operator turned
	// authentication off.
	Token string

	err error

	// roots holds roots already proven by their header's work, by height,
	// for rootTTL: one object's ancestry often names the same block more
	// than once, and a rate-limited public service should be asked once.
	mu    sync.Mutex
	roots map[uint32]provenRoot
}

type provenRoot struct {
	root chainhash.Hash
	at   time.Time
}

// rootTTL bounds how long a proven root is reused, so a reorganised tip is
// read again; rootCacheMax bounds how many are kept.
const (
	rootTTL      = 10 * time.Minute
	rootCacheMax = 10_000
)

var _ chaintracker.ChainTracker = (*Client)(nil)

// New returns a client for a header source specification (see Parse). A
// specification that does not parse yields a client whose every call returns
// the parse error, so a caller that cannot handle an error at construction
// still refuses rather than guessing.
func New(spec string) *Client {
	c, err := NewSource(spec)
	if err != nil {
		return &Client{Base: strings.TrimRight(spec, "/"), err: err}
	}
	return c
}

// maxBody bounds an answer before it is parsed. The header service is trusted
// to be honest about the chain, which is not the same as trusting it to be
// well behaved about response size.
const maxBody = 1 << 20

// ErrBodyTooLarge refuses a response above the bound.
var ErrBodyTooLarge = errors.New("headers: response body exceeds the bound")

// noProxyTransport is the transport behind the default client, and it takes
// no proxy. That is a decision, not an omission: this client answers "what
// root does height N commit to", which is the root of trust for every proof
// checked against it, and HTTP_PROXY in the environment would let whoever set
// that variable answer it from a host that appears nowhere in the caller's
// configuration or trace. resolve refuses environment proxies for discovery
// and hostset for host reads; refusing them here is the same rule where it
// costs most to break. A deployment that needs a proxy sets Client.HTTP,
// where the choice is visible.
//
// One transport for the package, as http.DefaultTransport is, so a run that
// checks many proofs reuses one connection pool.
var noProxyTransport = &http.Transport{
	Proxy: nil, // see the doc comment
	// Setting TLSClientConfig or DialContext disables automatic HTTP/2 unless
	// this is set, and the http.DefaultTransport these replaced had it on.
	// Losing a protocol version as a side effect of pinning a proxy policy is
	// the kind of change nobody notices until a deployment is slower.
	ForceAttemptHTTP2:   true,
	DialContext:         (&net.Dialer{Timeout: 10 * time.Second}).DialContext,
	TLSClientConfig:     &tls.Config{MinVersion: tls.VersionTLS12},
	TLSHandshakeTimeout: 10 * time.Second,
	MaxIdleConns:        4,
	IdleConnTimeout:     30 * time.Second,
}

// httpClient returns the caller's client when there is one, so a test or a
// deployment can supply its own policy, and otherwise the default.
func (c *Client) httpClient() *http.Client {
	if c.HTTP != nil {
		return c.HTTP
	}
	t := c.Timeout
	if t == 0 {
		t = 10 * time.Second
	}
	return &http.Client{Transport: noProxyTransport, Timeout: t}
}

// readAtMost reads up to limit+1 bytes WITHOUT judging the length, so the
// caller can act on the status code first. Refusing an oversized body before
// the status is read turns every padded error page into a size error and
// throws away the distinction the status carries, which is exactly the
// distinction this package is careful about elsewhere.
func readAtMost(r io.Reader, limit int64) ([]byte, error) {
	return io.ReadAll(io.LimitReader(r, limit+1))
}

// overBound reports a body that exceeded the bound. It is called once the
// status has been handled. Refusing rather than truncating is the point: a
// truncated answer parses as the wrong thing, or fails to parse with an
// error that names the wrong problem.
func overBound(b []byte, limit int64) error {
	if int64(len(b)) > limit {
		return fmt.Errorf("%w (%d bytes)", ErrBodyTooLarge, limit)
	}
	return nil
}

// retries429 is how many times a 429 answer is retried, with back-off from
// 500 ms (or the service's Retry-After), each wait capped at 8 s. A public
// header service rate-limits, and a busy answer is not a failed proof.
const retries429 = 4

func (c *Client) get(ctx context.Context, path string, into any) (int, error) {
	for attempt := 0; ; attempt++ {
		status, retryAfter, err := c.getOnce(ctx, path, into)
		if err != nil || status != http.StatusTooManyRequests || attempt >= retries429 {
			return status, err
		}
		wait := time.Duration(500<<attempt) * time.Millisecond
		if s, perr := strconv.Atoi(retryAfter); perr == nil && s >= 0 {
			wait = time.Duration(s) * time.Second
		}
		wait = min(wait, 8*time.Second)
		select {
		case <-ctx.Done():
			return status, ctx.Err()
		case <-time.After(wait):
		}
	}
}

// getOnce is one GET: the status, the Retry-After header, and the body
// decoded into into when the status is 200.
func (c *Client) getOnce(ctx context.Context, path string, into any) (int, string, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, strings.TrimRight(c.Base, "/")+path, nil)
	if err != nil {
		return 0, "", err
	}
	req.Header.Set("Accept", "application/json")
	if c.Token != "" {
		req.Header.Set("Authorization", "Bearer "+c.Token)
	}

	resp, err := c.httpClient().Do(req)
	if err != nil {
		return 0, "", err
	}
	defer resp.Body.Close()
	body, err := readAtMost(resp.Body, maxBody)
	if err != nil {
		return resp.StatusCode, "", err
	}
	// Status first. A 404 means the store does not hold that height yet, and
	// IsValidRootForHeight turns that into (false, nil) on purpose; a service
	// that padded its 404 page must not come back as a malformed answer.
	if resp.StatusCode != http.StatusOK {
		return resp.StatusCode, resp.Header.Get("Retry-After"), nil
	}
	if err := overBound(body, maxBody); err != nil {
		return resp.StatusCode, "", err
	}
	if err := json.Unmarshal(body, into); err != nil {
		return resp.StatusCode, "", fmt.Errorf("header service answered %d with a body that is not JSON: %w", resp.StatusCode, err)
	}
	return resp.StatusCode, "", nil
}

// IsValidRootForHeight reports whether root is the merkle root committed at
// height.
//
// A 404 is (false, nil): the bridge does not hold that height yet, which means
// the proof cannot be checked, not that anything is broken. Any OTHER non-ok
// status is an ERROR, and the distinction is load-bearing. Collapsing the two
// makes an unreachable or misconfigured header service look exactly like a
// forged proof, and a verifier that cannot tell those apart will either accept
// forgeries during an outage or reject good proofs during one, depending on
// which way it guessed.
func (c *Client) IsValidRootForHeight(ctx context.Context, root *chainhash.Hash, height uint32) (bool, error) {
	if root == nil {
		return false, nil
	}
	if c.err != nil {
		return false, c.err
	}
	if c.Kind != Native {
		c.mu.Lock()
		hit, ok := c.roots[height]
		c.mu.Unlock()
		if ok && time.Since(hit.at) < rootTTL {
			return hit.root == *root, nil
		}
		h, err := c.fullHeader(ctx, height)
		if err != nil || h == nil {
			return false, err
		}
		// The work is checked before the root is compared, so a forged header
		// is an error even when its root is the one the caller hoped for.
		if err := h.check(height, c.minDifficulty()); err != nil {
			return false, err
		}
		c.mu.Lock()
		if c.roots == nil || len(c.roots) >= rootCacheMax {
			c.roots = map[uint32]provenRoot{}
		}
		c.roots[height] = provenRoot{root: h.Root, at: time.Now()}
		c.mu.Unlock()
		return h.Root == *root, nil
	}
	var answer struct {
		Height     uint32 `json:"height"`
		MerkleRoot string `json:"merkleRoot"`
	}
	status, err := c.get(ctx, "/v1/root/"+strconv.FormatUint(uint64(height), 10), &answer)
	if err != nil {
		return false, err
	}
	switch status {
	case http.StatusOK:
	case http.StatusNotFound:
		return false, nil
	default:
		return false, fmt.Errorf("header service: root for height %d: status %d", height, status)
	}
	if answer.MerkleRoot == "" {
		return false, fmt.Errorf("header service: no merkleRoot for height %d", height)
	}
	// Compared as the SDK's display hex, which is how the service renders it.
	// Parsing to a hash and comparing bytes would work too; comparing the
	// strings makes a byte-order mistake on either side visible as a plain
	// mismatch rather than as a silent reversal.
	return strings.EqualFold(answer.MerkleRoot, root.String()), nil
}

// CurrentHeight reports the header service's tip.
//
// Needed as well as root validation, not instead of it: a health check
// reports how far the header source has got, and a service that answers roots
// while reporting height zero is a service that has not started.
func (c *Client) CurrentHeight(ctx context.Context) (uint32, error) {
	if c.err != nil {
		return 0, c.err
	}
	switch c.Kind {
	case WhatsOnChain:
		var info struct {
			Blocks uint32 `json:"blocks"`
		}
		status, err := c.get(ctx, "/chain/info", &info)
		if err != nil {
			return 0, err
		}
		if status != http.StatusOK {
			return 0, fmt.Errorf("header service: tip: status %d", status)
		}
		return info.Blocks, nil
	case Chaintracks:
		var env struct {
			Status string `json:"status"`
			Value  struct {
				Height uint32 `json:"height"`
			} `json:"value"`
		}
		status, err := c.get(ctx, "/height", &env)
		if err != nil {
			return 0, err
		}
		if status != http.StatusOK || env.Status != "success" {
			return 0, fmt.Errorf("header service: tip: status %d %q", status, env.Status)
		}
		return env.Value.Height, nil
	case BlockHeadersService, Arcade:
		var tip struct {
			Height *uint32 `json:"height"`
		}
		path := "/height"
		if c.Kind == BlockHeadersService {
			path = "/chain/tip/longest"
		}
		status, err := c.get(ctx, path, &tip)
		if err != nil {
			return 0, err
		}
		if status != http.StatusOK || tip.Height == nil {
			return 0, fmt.Errorf("header service: tip: status %d", status)
		}
		return *tip.Height, nil
	}
	var answer struct {
		Height uint32 `json:"height"`
		Hash   string `json:"hash"`
	}
	status, err := c.get(ctx, "/v1/tip", &answer)
	if err != nil {
		return 0, err
	}
	if status != http.StatusOK {
		return 0, fmt.Errorf("header service: tip: status %d", status)
	}
	return answer.Height, nil
}
