// Package headers is a chain tracker over the header read API of an overlay
// bridge (github.com/lightwebinc/overlay-bridge).
//
// It is the root of trust for every proof checked against it. A transaction
// is only as trustworthy as the headers its BUMP is checked against, so the
// question of WHO answers "what root does height N commit to" is the whole
// security question, not a configuration detail. Pointing this at a public
// header service would mean trusting that service to tell the truth about the
// chain; pointing it at a bridge that received the headers itself, off the
// same network that delivered the transaction, does not.
//
// It speaks HTTP and imports nothing from the bridge. That is deliberate:
// this module has exactly one direct dependency, and an HTTP contract plus a
// vendored fixture is a cheaper coupling than a Go dependency on a service.
// The fixtures in testdata/fixtures are the bridge's own generated bytes,
// copied verbatim, so a change to its wire shape fails here rather than in
// production.
package headers

import (
	"context"
	"crypto/tls"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/bsv-blockchain/go-sdk/chainhash"
	"github.com/bsv-blockchain/go-sdk/transaction/chaintracker"
)

// Client reads block headers from a bridge's native /v1 routes.
type Client struct {
	// Base is the bridge's header read API base, with no path suffix.
	Base string
	// HTTP is optional.
	HTTP *http.Client
	// Timeout defaults to 10s when HTTP is nil.
	Timeout time.Duration
}

var _ chaintracker.ChainTracker = (*Client)(nil)

// New returns a client for base.
func New(base string) *Client {
	return &Client{Base: strings.TrimRight(base, "/")}
}

// maxBody bounds an answer before it is parsed. The header service is trusted
// to be honest about the chain, which is not the same as trusting it to be
// well behaved about response size.
const maxBody = 1 << 20

// ErrBodyTooLarge refuses a response above the bound.
var ErrBodyTooLarge = errors.New("headers: response body exceeds the bound")

// noProxyTransport is the transport behind the default client, and it takes
// no proxy. That is a decision, not an omission: this client answers "what
// root does height N commit to", which is the root of trust for every proof
// checked against it, and HTTP_PROXY in the environment would let whoever set
// that variable answer it from a host that appears nowhere in the caller's
// configuration or trace. resolve refuses environment proxies for discovery
// and hostset for host reads; refusing them here is the same rule where it
// costs most to break. A deployment that needs a proxy sets Client.HTTP,
// where the choice is visible.
//
// One transport for the package, as http.DefaultTransport is, so a run that
// checks many proofs reuses one connection pool.
var noProxyTransport = &http.Transport{
	Proxy: nil, // see the doc comment
	// Setting TLSClientConfig or DialContext disables automatic HTTP/2 unless
	// this is set, and the http.DefaultTransport these replaced had it on.
	// Losing a protocol version as a side effect of pinning a proxy policy is
	// the kind of change nobody notices until a deployment is slower.
	ForceAttemptHTTP2:   true,
	DialContext:         (&net.Dialer{Timeout: 10 * time.Second}).DialContext,
	TLSClientConfig:     &tls.Config{MinVersion: tls.VersionTLS12},
	TLSHandshakeTimeout: 10 * time.Second,
	MaxIdleConns:        4,
	IdleConnTimeout:     30 * time.Second,
}

// httpClient returns the caller's client when there is one, so a test or a
// deployment can supply its own policy, and otherwise the default.
func (c *Client) httpClient() *http.Client {
	if c.HTTP != nil {
		return c.HTTP
	}
	t := c.Timeout
	if t == 0 {
		t = 10 * time.Second
	}
	return &http.Client{Transport: noProxyTransport, Timeout: t}
}

// readAtMost reads up to limit+1 bytes WITHOUT judging the length, so the
// caller can act on the status code first. Refusing an oversized body before
// the status is read turns every padded error page into a size error and
// throws away the distinction the status carries, which is exactly the
// distinction this package is careful about elsewhere.
func readAtMost(r io.Reader, limit int64) ([]byte, error) {
	return io.ReadAll(io.LimitReader(r, limit+1))
}

// overBound reports a body that exceeded the bound. It is called once the
// status has been handled. Refusing rather than truncating is the point: a
// truncated answer parses as the wrong thing, or fails to parse with an
// error that names the wrong problem.
func overBound(b []byte, limit int64) error {
	if int64(len(b)) > limit {
		return fmt.Errorf("%w (%d bytes)", ErrBodyTooLarge, limit)
	}
	return nil
}

func (c *Client) get(ctx context.Context, path string, into any) (int, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, strings.TrimRight(c.Base, "/")+path, nil)
	if err != nil {
		return 0, err
	}
	req.Header.Set("Accept", "application/json")

	resp, err := c.httpClient().Do(req)
	if err != nil {
		return 0, err
	}
	defer resp.Body.Close()
	body, err := readAtMost(resp.Body, maxBody)
	if err != nil {
		return resp.StatusCode, err
	}
	// Status first. A 404 means the store does not hold that height yet, and
	// IsValidRootForHeight turns that into (false, nil) on purpose; a service
	// that padded its 404 page must not come back as a malformed answer.
	if resp.StatusCode != http.StatusOK {
		return resp.StatusCode, nil
	}
	if err := overBound(body, maxBody); err != nil {
		return resp.StatusCode, err
	}
	if err := json.Unmarshal(body, into); err != nil {
		return resp.StatusCode, fmt.Errorf("header service answered %d with a body that is not JSON: %w", resp.StatusCode, err)
	}
	return resp.StatusCode, nil
}

// IsValidRootForHeight reports whether root is the merkle root committed at
// height.
//
// A 404 is (false, nil): the bridge does not hold that height yet, which means
// the proof cannot be checked, not that anything is broken. Any OTHER non-ok
// status is an ERROR, and the distinction is load-bearing. Collapsing the two
// makes an unreachable or misconfigured header service look exactly like a
// forged proof, and a verifier that cannot tell those apart will either accept
// forgeries during an outage or reject good proofs during one, depending on
// which way it guessed.
func (c *Client) IsValidRootForHeight(ctx context.Context, root *chainhash.Hash, height uint32) (bool, error) {
	if root == nil {
		return false, nil
	}
	var answer struct {
		Height     uint32 `json:"height"`
		MerkleRoot string `json:"merkleRoot"`
	}
	status, err := c.get(ctx, "/v1/root/"+strconv.FormatUint(uint64(height), 10), &answer)
	if err != nil {
		return false, err
	}
	switch status {
	case http.StatusOK:
	case http.StatusNotFound:
		return false, nil
	default:
		return false, fmt.Errorf("header service: root for height %d: status %d", height, status)
	}
	if answer.MerkleRoot == "" {
		return false, fmt.Errorf("header service: no merkleRoot for height %d", height)
	}
	// Compared as the SDK's display hex, which is how the service renders it.
	// Parsing to a hash and comparing bytes would work too; comparing the
	// strings makes a byte-order mistake on either side visible as a plain
	// mismatch rather than as a silent reversal.
	return strings.EqualFold(answer.MerkleRoot, root.String()), nil
}

// CurrentHeight reports the header service's tip.
//
// Needed as well as root validation, not instead of it: a health check
// reports how far the header source has got, and a service that answers roots
// while reporting height zero is a service that has not started.
func (c *Client) CurrentHeight(ctx context.Context) (uint32, error) {
	var answer struct {
		Height uint32 `json:"height"`
		Hash   string `json:"hash"`
	}
	status, err := c.get(ctx, "/v1/tip", &answer)
	if err != nil {
		return 0, err
	}
	if status != http.StatusOK {
		return 0, fmt.Errorf("header service: tip: status %d", status)
	}
	return answer.Height, nil
}
